const fs = require('node:fs');
const path = require('node:path');

// Keep the reading hierarchy identical in both variants.
const palettes = {
  light: {
    name: 'Function Focus Light', type: 'light',
    bg: '#FAFBFC', fg: '#343C45', surface: '#F1F3F5', raised: '#FFFFFF',
    border: '#DAE0E5', muted: '#69727D', comment: '#6E747A', string: '#646F64',
    fn: '#005FCC', builtin: '#176F80', control: '#A33442', keyword: '#5E546E',
    parameter: '#A35F00', typeName: '#74489C', number: '#8F5C11',
    operator: '#4E5D6D', punctuation: '#687280', accent: '#005FCC',
    selection: '#CFE3FF', inactiveSelection: '#E2EAF3', line: '#F0F4F9',
    guide: '#DDE3EA', activeGuide: '#8AABCF', match: '#CFEBD9',
    error: '#B52D3D', warning: '#916100', success: '#24734B',
    bracket: ['#476988', '#80692B', '#745688'],
    terminal: ['#343C45', '#B52D3D', '#24734B', '#916100', '#005FCC', '#74489C', '#176F80', '#D4DAE0']
  },
  dark: {
    name: 'Function Focus Dark', type: 'dark',
    bg: '#1B1E22', fg: '#D2D7DF', surface: '#22262B', raised: '#282D33',
    border: '#3C434D', muted: '#A1A9B3', comment: '#969CA4', string: '#A3B19F',
    fn: '#6AC4FF', builtin: '#7ABFC0', control: '#FFA0A8', keyword: '#B7ABC9',
    parameter: '#FFD166', typeName: '#C3A6E8', number: '#DEBC7D',
    operator: '#B8C4D4', punctuation: '#9BA7B6', accent: '#6AC4FF',
    selection: '#344C65', inactiveSelection: '#303A46', line: '#23282F',
    guide: '#363D47', activeGuide: '#6483A4', match: '#355044',
    error: '#FF919E', warning: '#E8C376', success: '#8BCDAB',
    bracket: ['#9AB9D6', '#C8B784', '#BDA5D5'],
    terminal: ['#555E69', '#FF919E', '#8BCDAB', '#E8C376', '#6AC4FF', '#C3A6E8', '#7ABFC0', '#D2D7DF']
  }
};

function theme(p, options = {}) {
  const callBold = options.callBold !== false;
  const parameterBold = options.parameterBold === true;
  const token = (name, scope, foreground, fontStyle = '') => ({ name, scope, settings: { foreground, fontStyle } });
  const style = (foreground, bold = false) => ({ foreground, bold, italic: false });
  const colors = {
    'foreground': p.fg,
    'descriptionForeground': p.muted,
    'disabledForeground': p.muted,
    'focusBorder': p.accent,
    'errorForeground': p.error,
    'textLink.foreground': p.accent,
    'textLink.activeForeground': p.accent,
    'textCodeBlock.background': p.surface,
    'textBlockQuote.background': p.surface,
    'textBlockQuote.border': p.border,
    'textPreformat.foreground': p.builtin,
    'textSeparator.foreground': p.border,
    'widget.border': p.border,
    'editor.background': p.bg,
    'editor.foreground': p.fg,
    'editorCursor.foreground': p.accent,
    'editorLineNumber.foreground': p.muted,
    'editorLineNumber.activeForeground': p.accent,
    'editor.lineHighlightBackground': p.line,
    'editor.selectionBackground': p.selection,
    'editor.inactiveSelectionBackground': p.inactiveSelection,
    'editor.selectionHighlightBackground': p.selection + '70',
    'editor.wordHighlightBackground': p.selection + '60',
    'editor.wordHighlightStrongBackground': p.selection + 'A0',
    'editor.findMatchBackground': p.match,
    'editor.findMatchBorder': p.success,
    'editor.findMatchHighlightBackground': p.match + '80',
    'editorIndentGuide.background1': p.guide,
    'editorIndentGuide.activeBackground1': p.activeGuide,
    'editorBracketMatch.background': p.selection + '70',
    'editorBracketMatch.border': p.activeGuide,
    'editorBracketHighlight.unexpectedBracket.foreground': p.error,
    'editorWhitespace.foreground': p.guide,
    'editorRuler.foreground': p.guide,
    'editorGutter.background': p.bg,
    'editorGutter.addedBackground': p.success,
    'editorGutter.modifiedBackground': p.accent,
    'editorGutter.deletedBackground': p.error,
    'editorError.foreground': p.error,
    'editorWarning.foreground': p.warning,
    'editorInfo.foreground': p.accent,
    'editorHint.foreground': p.muted,
    'editorOverviewRuler.border': '#00000000',
    'editorWidget.background': p.raised,
    'editorWidget.foreground': p.fg,
    'editorWidget.border': p.border,
    'editorHoverWidget.background': p.raised,
    'editorHoverWidget.foreground': p.fg,
    'editorHoverWidget.border': p.border,
    'editorSuggestWidget.background': p.raised,
    'editorSuggestWidget.foreground': p.fg,
    'editorSuggestWidget.selectedBackground': p.selection,
    'editorSuggestWidget.highlightForeground': p.accent,
    'editorSuggestWidget.border': p.border,
    'editorInlayHint.foreground': p.muted,
    'editorInlayHint.background': p.surface,
    'editorCodeLens.foreground': p.muted,
    'editorStickyScroll.background': p.bg,
    'editorStickyScroll.border': p.border,
    'editorGroup.border': p.border,
    'editorGroupHeader.tabsBackground': p.surface,
    'editorGroupHeader.tabsBorder': p.border,
    'tab.activeBackground': p.bg,
    'tab.activeForeground': p.fg,
    'tab.activeBorderTop': p.accent,
    'tab.inactiveBackground': p.surface,
    'tab.inactiveForeground': p.muted,
    'tab.border': p.border,
    'sideBar.background': p.surface,
    'sideBar.foreground': p.fg,
    'sideBar.border': p.border,
    'sideBarSectionHeader.background': p.surface,
    'sideBarSectionHeader.foreground': p.muted,
    'sideBarSectionHeader.border': p.border,
    'activityBar.background': p.surface,
    'activityBar.foreground': p.accent,
    'activityBar.inactiveForeground': p.muted,
    'activityBar.border': p.border,
    'activityBarBadge.background': p.accent,
    'activityBarBadge.foreground': p.bg,
    'titleBar.activeBackground': p.surface,
    'titleBar.activeForeground': p.fg,
    'titleBar.inactiveBackground': p.surface,
    'titleBar.inactiveForeground': p.muted,
    'titleBar.border': p.border,
    'statusBar.background': p.surface,
    'statusBar.foreground': p.muted,
    'statusBar.border': p.border,
    'statusBar.noFolderBackground': p.surface,
    'statusBar.debuggingBackground': p.surface,
    'statusBar.debuggingForeground': p.warning,
    'statusBarItem.remoteBackground': p.surface,
    'statusBarItem.remoteForeground': p.builtin,
    'panel.background': p.bg,
    'panel.border': p.border,
    'panelTitle.activeForeground': p.fg,
    'panelTitle.inactiveForeground': p.muted,
    'panelTitle.activeBorder': p.accent,
    'input.background': p.raised,
    'input.foreground': p.fg,
    'input.border': p.border,
    'input.placeholderForeground': p.muted,
    'inputOption.activeBackground': p.selection,
    'inputOption.activeBorder': p.accent,
    'dropdown.background': p.raised,
    'dropdown.foreground': p.fg,
    'dropdown.border': p.border,
    'button.background': p.accent,
    'button.foreground': p.bg,
    'button.hoverBackground': p.builtin,
    'button.secondaryBackground': p.inactiveSelection,
    'button.secondaryForeground': p.fg,
    'badge.background': p.inactiveSelection,
    'badge.foreground': p.fg,
    'list.activeSelectionBackground': p.selection,
    'list.activeSelectionForeground': p.fg,
    'list.inactiveSelectionBackground': p.inactiveSelection,
    'list.inactiveSelectionForeground': p.fg,
    'list.hoverBackground': p.line,
    'list.focusBackground': p.selection,
    'list.focusForeground': p.fg,
    'list.highlightForeground': p.accent,
    'list.errorForeground': p.error,
    'list.warningForeground': p.warning,
    'quickInput.background': p.raised,
    'quickInput.foreground': p.fg,
    'quickInputList.focusBackground': p.selection,
    'notifications.background': p.raised,
    'notifications.foreground': p.fg,
    'notifications.border': p.border,
    'scrollbarSlider.background': p.muted + '30',
    'scrollbarSlider.hoverBackground': p.muted + '55',
    'scrollbarSlider.activeBackground': p.muted + '70',
    'breadcrumb.foreground': p.muted,
    'breadcrumb.focusForeground': p.accent,
    'breadcrumb.activeSelectionForeground': p.fg,
    'minimap.selectionHighlight': p.activeGuide,
    'gitDecoration.modifiedResourceForeground': p.builtin,
    'gitDecoration.untrackedResourceForeground': p.success,
    'gitDecoration.deletedResourceForeground': p.error,
    'gitDecoration.ignoredResourceForeground': p.muted,
    'diffEditor.insertedTextBackground': p.success + '20',
    'diffEditor.removedTextBackground': p.error + '20',
    'terminal.background': p.bg,
    'terminal.foreground': p.fg,
    'terminalCursor.foreground': p.accent,
    'terminal.selectionBackground': p.selection,
    'symbolIcon.functionForeground': p.fn,
    'symbolIcon.methodForeground': p.fn,
    'symbolIcon.classForeground': p.typeName,
    'symbolIcon.variableForeground': p.fg,
    'symbolIcon.parameterForeground': p.parameter
  };
  for (let i = 1; i <= 6; i++) colors['editorBracketHighlight.foreground' + i] = p.bracket[(i - 1) % 3];
  ['Black', 'Red', 'Green', 'Yellow', 'Blue', 'Magenta', 'Cyan', 'White'].forEach((name, i) => {
    colors['terminal.ansi' + name] = p.terminal[i];
    colors['terminal.ansiBright' + name] = p.terminal[i];
  });
  return {
    $schema: 'vscode://schemas/color-theme', name: p.name, type: p.type,
    semanticHighlighting: true, colors,
    tokenColors: [
      token('Ordinary names', ['variable', 'support.variable', 'entity.name.variable', 'meta.definition.variable'], p.fg),
      token('Quiet strings and docstrings', ['string', 'string.quoted.docstring', 'string.unquoted', 'markup.inline.raw'], p.string),
      token('Readable quiet comments', ['comment', 'punctuation.definition.comment'], p.comment),
      token('Literal punctuation', ['punctuation.definition.string'], p.string),
      token('String escapes', ['constant.character.escape'], p.builtin),
      token('Code inside interpolation', ['meta.embedded', 'meta.fstring.python'], p.fg),
      token('Keywords', ['keyword', 'storage.type', 'storage.modifier'], p.keyword),
      token('Control flow and returns', ['keyword.control', 'keyword.control.flow', 'keyword.control.conditional', 'keyword.control.loop', 'keyword.control.exception', 'keyword.control.import', 'keyword.other.using'], p.control, 'bold'),
      token('Definition boundaries', ['storage.type.function', 'storage.type.class', 'storage.type.function.arrow'], p.control, 'bold'),
      token('Operators', ['keyword.operator'], p.operator),
      token('Word operators', ['keyword.operator.logical.python', 'keyword.operator.wordlike', 'keyword.operator.expression.await'], p.control),
      token('Punctuation', ['punctuation.separator', 'punctuation.terminator', 'punctuation.section', 'punctuation.definition.arguments', 'punctuation.definition.parameters', 'meta.brace'], p.punctuation),
      token('Function and method declarations', ['entity.name.function'], p.fn, 'bold'),
      token('Function and method calls', ['meta.function-call entity.name.function', 'meta.function-call.generic.python', 'meta.function-call.python', 'meta.method-call entity.name.function', 'support.function'], p.fn, callBold ? 'bold' : ''),
      token('Call argument names', ['meta.function-call.arguments', 'meta.function-call.arguments.python'], p.fg),
      token('Built-in helpers', ['support.function.builtin', 'support.function.builtins'], p.builtin, callBold ? 'bold' : ''),
      token('Parameters', ['variable.parameter', 'entity.name.variable.parameter'], p.parameter, parameterBold ? 'bold' : ''),
      token('Receiver self and cls', ['variable.language', 'variable.parameter.function.language.special.self.python', 'variable.parameter.function.language.special.cls.python', 'variable.language.special.self.python', 'variable.language.special.cls.python'], p.muted),
      token('Classes and types', ['entity.name.type', 'entity.name.class', 'support.type', 'support.class', 'entity.other.inherited-class'], p.typeName),
      token('Modules and namespaces', ['entity.name.namespace', 'support.module', 'support.other.module'], p.fg),
      token('Decorators', ['entity.name.function.decorator', 'meta.function.decorator', 'punctuation.definition.decorator'], p.typeName),
      token('Numbers and boolean values', ['constant.numeric', 'constant.language', 'variable.other.constant', 'variable.other.enummember'], p.number),
      token('Configuration keys', ['support.type.property-name.json', 'support.type.property-name.jsonc', 'entity.name.tag.yaml', 'meta.object-literal.key'], p.fg),
      token('Markdown headings', ['markup.heading', 'entity.name.section'], p.fn, 'bold'),
      token('Markdown emphasis', ['markup.bold'], p.fg, 'bold'),
      token('Markdown italics', ['markup.italic'], p.fg, 'italic'),
      token('Links', ['markup.underline.link', 'string.other.link'], p.builtin),
      token('Added text', ['markup.inserted'], p.success),
      token('Removed text', ['markup.deleted'], p.error),
      token('Invalid syntax', ['invalid'], p.error)
    ],
    semanticTokenColors: {
      'variable': style(p.fg), 'property': style(p.fg),
      'parameter': style(p.parameter, parameterBold), 'selfParameter': style(p.muted), 'clsParameter': style(p.muted),
      'function': style(p.fn, callBold), 'method': style(p.fn, callBold),
      'function.declaration': style(p.fn, true), 'function.definition': style(p.fn, true),
      'method.declaration': style(p.fn, true), 'method.definition': style(p.fn, true),
      'function.defaultLibrary': style(p.builtin, callBold), 'method.defaultLibrary': style(p.builtin, callBold),
      'class': style(p.typeName), 'class.declaration': style(p.typeName, true),
      'type': style(p.typeName), 'typeParameter': style(p.typeName), 'interface': style(p.typeName),
      'namespace': style(p.fg), 'module': style(p.fg),
      'decorator': style(p.typeName), 'keyword': style(p.control, true),
      'operator': style(p.operator), 'string': style(p.string), 'comment': style(p.comment),
      'number': style(p.number), 'enumMember': style(p.number), 'variable.readonly': style(p.number)
    }
  };
}

if (require.main === module) {
  const output = path.join(__dirname, 'extension', 'themes');
  fs.mkdirSync(output, { recursive: true });
  for (const [variant, palette] of Object.entries(palettes)) {
    fs.writeFileSync(path.join(output, 'function-focus-' + variant + '.json'), JSON.stringify(theme(palette), null, 2) + '\n');
  }
  console.log('Built Function Focus Light and Dark.');
}
module.exports = { palettes, theme };
